### ISSUE TITLE
Possibility to have empty setUpNotice()?

### ISSUE THREAD

**Issue by nlohmann** [lascic/UIOnboarding#11]
Is there a way to configure away the text generated by `setUpNotice()`? I just don't need this text.

**Comment by lascic** [comment]
Thank you for reaching out. I just pushed [v2.0.1](https://github.com/lascic/UIOnboarding/releases/tag/2.0.1), making the notice configuration optional.

**Comment by nlohmann** [comment]
Thanks for the quick response! Works like a charm!

Keep up the good work!
