### ISSUE TITLE
Error when executing app in Xcode 15 beta / iOS 17

### ISSUE THREAD

**Issue by bircni** [lascic/UIOnboarding#15]
The following error occurs:
`UIOnboarding/UIOnboardingViewController.swift:98: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value`

**Comment by lascic** [comment]
Thanks for reporting. Will look into this.

**Comment by lascic** [comment]
Is the error still occurring? Everything seems to be running ok on Xcode 17 beta 5. If it still happens, can you provide more context? A screenshot of the Report navigator would also be appreciated.

Line 98 could mean either the parent or child stack view is not properly initialized. But so far I have no problems. Can you help me replicate the issue?

**Comment by lascic** [comment]
Any updates on the issue? Running on Xcode 15 beta 7, as of today, didn't produce the error.

**Comment by FelixLisczyk** [comment]
I was able to reproduce the crash when running the "UIOnboarding SwiftUI" demo project with the latest Xcode 17 beta 8. The UIKit demo projects are not affected.

`UIOnboarding/UIOnboardingViewController.swift:94: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value`

**Comment by FelixLisczyk** [comment]
I've created PR #19 to fix this issue. Could you please give it a try? @bircni, @lascic
