### ISSUE TITLE
SF Symbol Support

### ISSUE THREAD

**Issue by fatihdurmaz** [lascic/UIOnboarding#23]
Are you planning to add SF Symbol support?

**Comment by lascic** [comment]
Thank you for your comment.

By default, you can instantiate `UIImage` with the `.init(systemName: "")` constructor. Have a further look at the [documentation](https://developer.apple.com/documentation/uikit/uiimage/configuring_and_displaying_symbol_images_in_your_ui) and [website](https://developer.apple.com/design/human-interface-guidelines/sf-symbols) for use of SF Symbols in UIKit.

The following example shows how you can further customize your image instance.

<img align="right" width="315" src="https://github.com/lascic/UIOnboarding/assets/34413704/92df63bd-6316-423c-a344-2f5a71f469bf" alt="Example">

```swift
// UIOnboardingHelper.swift

UIImage(systemName: "ellipsis.curlybraces")?.applyingSymbolConfiguration(.init(paletteColors: [.label, UIColor.init(named: "camou") ?? UIColor.init(red: 0.654, green: 0.618, blue: 0.494, alpha: 1.0)])) ?? .init()
```
<br/>
If there's another specific inquiry regarding SF Symbols, please let me know. Specification appreciated. Thanks.
