### ISSUE TITLE
Enhancement: Adjust Font size

### ISSUE THREAD

**Issue by hensch7** [lascic/UIOnboarding#8]
Hey there, 

I don't know how easily you could implement this, but it would be a very nice option to make the subtitle text of each bullet point a bit smaller.
Currently, it's the same size as the title above it, just not bold. 
I'd love to see a size different or at least an option for it.

If this is too much hassle due to the sizing adjustments necessary, I'd understand it. 

Thanks in advance
P.S.: I love your repo, this Onboarding View is awesome!!

**Comment by lascic** [comment]
Hey, thank you so much for your comment on UIOnboarding.

I can definitely make something for the font size of the feature title and body to be customisable in the future.

**Comment by lascic** [comment]
v2.0.2 now supports custom font sizing for feature cell labels.
