### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by 224XS** [lascic/UIOnboarding#9]
I added the pkg with SPM and import the library. My code has a small stub which runs the UIOnboarding startup sequence:

```
    func doOnBoarding() -> Void {
        setUp()
        presentOnboarding()
    }
    
    @objc private func presentOnboarding() {
        let onboardingController: UIOnboardingViewController = .init(withConfiguration: .setUp())
        onboardingController.delegate = self
        navigationController?.present(onboardingController, animated: false)
    }

```
I get Error    "Type 'UIOnboardingViewConfiguration' has no member 'setUp'".   in the .init(withConfiguration: .setUp() )
Any thoughts?

**Comment by lascic** [comment]
I managed to recreate the error. It looks like `.setUp` is not a type member of `UIOnboardingViewConfiguration` meaning that something is missing in the extension. In this case, the code should look the following:

```swift
extension UIOnboardingViewConfiguration {
    static func setUp() -> UIOnboardingViewConfiguration {
        .init(appIcon: UIOnboardingHelper.setUpIcon(),
              firstTitleLine: UIOnboardingHelper.setUpFirstTitleLine(),
              secondTitleLine: UIOnboardingHelper.setUpSecondTitleLine(),
              features: UIOnboardingHelper.setUpFeatures(),
              textViewConfiguration: UIOnboardingHelper.setUpNotice(),
              buttonConfiguration: UIOnboardingHelper.setUpButton())
    }
}
``` 

Make sure you're extending from `UIOnboardingViewConfiguration` and check for any syntax issues (e.g. missing `static` keyword).

Thanks a lot for reaching out. If you encounter further issues I'm happy to help.

**Comment by 224XS** [comment]
Thanks Lascic for the quick response!!
scanning through my project with the SPM installed, the setup method only exists in the two Demos, not in source/
When I add your extension to UIOnboardingViewConfiguration with setup(),  to my main ViewController, I get a "can not find UIOnboardingHelper in scope" on every line.


Where should I best stick this chuck of code?

**Comment by 224XS** [comment]
I overlooked the onboard data file, UIOnboardingHelper.swift. Its included now with adding an "import UIOnboarding" at the top. Then the only remaining error concerned the icon inits which needed to be unwrapped. 
Now working!  
I breezed too quickly through the install section, but others might find it help to just note there that one must add or modify the UIOnboardingHelper.swift file!
